
services:
# Database
  postgres-db:
    image: postgres:15-alpine
    container_name: elei-postgres
    restart: always
    environment:
       POSTGRES_USER: ${POSTGRES_USER:-postgres}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
       POSTGRES_DB: ${POSTGRES_DB:-elei}
    ports:
      - "5432:5432"
    volumes:
      - elei-pg-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: elei-backend
    restart: always
    environment:
      DB_HOST: postgres-db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASS: ${POSTGRES_PASSWORD:-root}
      DB_NAME: ${POSTGRES_DB:-elei}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db



  frontend:
    build:
      context: ./frontend
    container_name: elei-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend


volumes:
  elei-pg-data:
