/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/settings/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update password
         * @description Allows the authenticated user to update their password by providing the current password and a new password
         */
        put: operations["updatePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update email
         * @description Allows the authenticated user to update their registered email address
         */
        put: operations["updateEmail"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate daily protocol
         * @description Updates user streak and awards daily bonus XP
         */
        post: operations["dailyCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/purchase/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purchase item
         * @description Allows the authenticated user to purchase an item from the shop using their in-game currency balance. The item is transferred to the user's inventory upon successful purchase.
         */
        post: operations["purchaseItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account in the Elei system
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user
         * @description Returns a JWT token to access protected endpoints
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an activity
         * @description Adds a new task or activity for the current user
         */
        post: operations["createActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete an activity
         * @description Awards experience points for completing activity units
         */
        post: operations["completeActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Returns basic profile data for the currently authenticated user
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get wallet balance
         * @description Returns the current in-game currency balance of the authenticated user.
         */
        get: operations["getWalletBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available items
         * @description Returns a list of items currently available for purchase in the shop, including their price and stock information.
         */
        get: operations["getAvailableItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user quests
         * @description Returns the list of quests and current progress for the authenticated citizen
         */
        get: operations["getUserQuests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the leaderboard
         * @description Returns a sorted array of the top citizens of Elei based on their experience.
         */
        get: operations["getTopDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system telemetry
         * @description Returns global system statistics. Requires ADMIN role
         */
        get: operations["getSystemTelemetry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user statistics
         * @description Returns aggregated activity statistics for the current user
         */
        get: operations["getActivityStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activity feed
         * @description Returns a list of recent activities to display in the feed
         */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an activity
         * @description Permanently removes an activity by its ID
         */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request payload for updating a user's password */
        UpdatePasswordRequest: {
            /** @description The current password for the user */
            currentPassword: string;
            /**
             * @description The new password for the user
             * @example securePass123!
             */
            newPassword: string;
        };
        /** @description Request payload for updating a user's email address */
        UpdateEmailRequest: {
            /**
             * Format: email
             * @description The new email address for the user
             * @example admin@elei.com
             */
            newEmail: string;
        };
        /** @description Data transfer object for user registration */
        RegisterRequest: {
            /**
             * @description Desired unique username
             * @example acrobtw
             */
            username: string;
            /**
             * Format: email
             * @description User's email address
             * @example admin@elei.com
             */
            email: string;
            /**
             * @description Account password
             * @example securePass123!
             */
            password: string;
        };
        /** @description User registration response with JWT token and status details */
        RegisterResponse: {
            /**
             * Format: int32
             * @description HTTP status code or internal operation status
             * @example 200
             */
            status: number;
            /**
             * @description Informational message regarding the registration result
             * @example User successfully registered
             */
            message: string;
            /**
             * @description The registered username
             * @example acrobtw
             */
            username: string;
            /**
             * @description JWT access token for immediate API authorization
             * @example eyJhbGciOiJIUzI1NiIsInR5c...
             */
            token: string;
            /**
             * Format: date-time
             * @description Timestamp of the successful registration process
             */
            timestamp: string;
        };
        /** @description Data transfer object for user authentication */
        LoginRequest: {
            /**
             * @description User's registered email or username
             * @example admin@elei.com
             */
            username: string;
            /**
             * @description Account password
             * @example securePass123!
             */
            password: string;
        };
        /** @description Authentication response containing the JWT token */
        LoginResponse: {
            /**
             * Format: int32
             * @description HTTP status code
             * @example 200
             */
            status: number;
            /**
             * @description Authenticated username
             * @example acrobtw
             */
            username: string;
            /** @description JWT Access Token */
            token: string;
            /**
             * Format: date-time
             * @description Timestamp of login
             */
            timestamp: string;
        };
        /** @description Payload for creating a new user activity */
        CreateActivityDto: {
            /**
             * @description Name of the activity
             * @example Read Spring Boot Documentation
             */
            name: string;
            /**
             * Format: int32
             * @description Experience points multiplier for this specific activity
             * @example 1
             */
            pointsMultiplier: number;
            /**
             * @description Measurement unit for the activity (e.g., pages, hours, tasks)
             * @example pages
             */
            unitName: string;
        };
        /** @description Payload for submitting progress on a specific activity */
        ActivityCompletionDto: {
            /**
             * Format: int64
             * @description Unique identifier of the target activity
             * @example 42
             */
            activityId: number;
            /**
             * Format: int32
             * @description Amount of units completed in this transaction
             * @example 1
             */
            unitsCompleted: number;
        };
        /** @description Basic profile information of the user */
        UserProfileResponse: {
            /**
             * @description User's unique username
             * @example acrobtw
             */
            username: string;
            /**
             * Format: email
             * @description User's registered email address
             * @example admin@elei.com
             */
            email: string;
            /**
             * @description User's provider
             * @example GITHUB
             * @enum {string}
             */
            provider: "LOCAL" | "GOOGLE" | "GITHUB";
            /**
             * @description List of dates the user was active in YYY-MM-DD format
             * @example [
             *       "2026-05-30",
             *       "2026-05-31"
             *     ]
             */
            activeDays: string[];
            /**
             * Format: int32
             * @description User's current level
             * @example 2
             */
            level: number;
            /**
             * Format: int64
             * @description Total accumulated experience
             * @example 150
             */
            totalExperience: number;
            /**
             * Format: int64
             * @description Experience required for the next level
             * @example 300
             */
            nextLevelExperience: number;
            /**
             * @description Citizen rank title
             * @example Novice
             */
            rank: string;
        };
        ShopItem: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** Format: int64 */
            price?: number;
            /** Format: int32 */
            stock?: number;
        };
        /** @description User's progress on a specific quest */
        QuestProgressDto: {
            /**
             * Format: int64
             * @description Unique ID of the quest
             */
            questId?: number;
            /**
             * @description Name of the quest
             * @example First Blood
             */
            title?: string;
            /** @description Detailed lore/description of the quest */
            description?: string;
            /**
             * Format: int32
             * @description Current progress count
             * @example 1
             */
            currentCount?: number;
            /**
             * Format: int32
             * @description Target count required to complete the quest
             * @example 5
             */
            targetCount?: number;
            /**
             * Format: int32
             * @description Experience reward upon completion
             * @example 100
             */
            rewardXp?: number;
            /** @description Is the quest fully completed and reward claimed? */
            isCompleted?: boolean;
        };
        /** @description Single entry in the global leaderboard */
        LeaderboardEntryDto: {
            /**
             * Format: int64
             * @description Unique user identifier
             * @example 1
             */
            id: number;
            /**
             * @description User's display name
             * @example acrobtw
             */
            username: string;
            /**
             * Format: int64
             * @description Total accumulated experience points
             * @example 15420
             */
            score: number;
        };
        /** @description Global system telemetry and statistics for the admin dashboard */
        SystemStatsDto: {
            /**
             * Format: int64
             * @description Total number of registered users
             * @example 1024
             */
            totalUsers: number;
            /**
             * Format: int64
             * @description Total number of active tasks/activities created
             * @example 5430
             */
            totalActivities: number;
            /**
             * Format: int64
             * @description Total number of experience logs recorded across the system
             * @example 25000
             */
            totalExperienceLogs: number;
        };
        /** @description User's progress details within a specific activity category */
        ActivityProgressDto: {
            /**
             * Format: int64
             * @description Unique identifier of the activity
             * @example 42
             */
            activityId: number;
            /**
             * @description Name of the activity or category
             * @example Reading Documentation
             */
            name: string;
            /**
             * Format: int32
             * @description Experience multiplier for this specific category
             * @example 2
             */
            pointsMultiplier: number;
            /**
             * Format: int32
             * @description Total experience earned by the user in this category
             * @example 450
             */
            userCategoryExperience: number;
            /**
             * @description Measurement unit for the activity
             * @example pages
             */
            unitName: string;
        };
        /** @description Aggregated statistics and progression data for a user */
        UserStatsDto: {
            /**
             * Format: int64
             * @description Total accumulated experience points
             * @example 4500
             */
            totalExperience: number;
            /**
             * Format: int64
             * @description Current calculated user level
             * @example 12
             */
            currentLevel: number;
            /**
             * Format: int64
             * @description Total experience required to reach the next level
             * @example 5000
             */
            nextLevelXp: number;
            /** @description Breakdown of progress by individual activity categories */
            categories: components["schemas"]["ActivityProgressDto"][];
        };
        /** @description A single event in the user's recent activity feed */
        ActivityFeedItemDto: {
            /**
             * Format: int64
             * @description Unique identifier of the log entry
             * @example 9876
             */
            logId: number;
            /**
             * @description Name of the completed activity
             * @example Read Spring Boot Docs
             */
            activityName: string;
            /**
             * Format: int32
             * @description Number of units completed during this event
             * @example 15
             */
            unitsCompleted: number;
            /**
             * @description Measurement unit of the activity
             * @example pages
             */
            unitName: string;
            /**
             * Format: int32
             * @description Experience points awarded for this transaction
             * @example 30
             */
            earnedXp: number;
            /**
             * Format: date-time
             * @description Timestamp when the activity was completed
             */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updatePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    updateEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    dailyCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    purchaseItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    createActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCompletionDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    getWalletBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    getAvailableItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShopItem"][];
                };
            };
        };
    };
    getUserQuests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestProgressDto"][];
                };
            };
        };
    };
    getTopDashboard: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeaderboardEntryDto"][];
                };
            };
        };
    };
    getSystemTelemetry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemStatsDto"];
                };
            };
        };
    };
    getActivityStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserStatsDto"];
                };
            };
        };
    };
    getFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityFeedItemDto"][];
                };
            };
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
